/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json */
        get: operations["api_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_campaigns_list"];
        put?: never;
        post: operations["api_v1_campaigns_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_campaigns_retrieve"];
        put: operations["api_v1_campaigns_update"];
        post?: never;
        delete: operations["api_v1_campaigns_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_v1_campaigns_partial_update"];
        trace?: never;
    };
    "/api/v1/sliders/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_sliders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sliders/{slug}/slides/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_sliders_slides_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials. */
        post: operations["api_v1_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid. */
        post: operations["api_v1_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Campaign: {
            readonly id: number;
            /**
             * Дата создания
             * Format: date-time
             */
            readonly created_date: string;
            /**
             * Дата редактирования
             * Format: date-time
             */
            readonly edited_date: string;
            /** Статус акции */
            campaign_status?: components["schemas"]["CampaignStatusEnum"];
            /** Комментарий администратора */
            admin_comment?: string;
            /** Название */
            title?: string;
            /**
             * Логотип акции
             * Format: uri
             */
            logo_image?: string;
            /**
             * Изображение акции
             * Format: uri
             */
            campaign_image?: string;
            /** Короткое описание */
            short_description?: string;
            /** Текст наклейки */
            sticker_text?: string;
            /** Вознаграждение */
            award?: number;
            /** Квота участников */
            quota?: number;
            /**
             * Дата окончания акции
             * Format: date-time
             */
            end_date: string;
            /**
             * Дата одобрения акции
             * Format: date
             */
            approve_date?: string | null;
            /**
             * Баланс акции
             * Format: decimal
             */
            campaign_balance?: string;
            /** Порядковый номер */
            num?: number;
            /** Рекламодатель */
            advertiser: number;
        };
        /**
         * @description * `0` - Нет
         *     * `1` - На одобрении
         *     * `2` - Активна
         *     * `3` - Отклонена
         *     * `4` - Завершена
         *     * `5` - Удалена
         * @enum {integer}
         */
        CampaignStatusEnum: 0 | 1 | 2 | 3 | 4 | 5;
        PatchedCampaign: {
            readonly id?: number;
            /**
             * Дата создания
             * Format: date-time
             */
            readonly created_date?: string;
            /**
             * Дата редактирования
             * Format: date-time
             */
            readonly edited_date?: string;
            /** Статус акции */
            campaign_status?: components["schemas"]["CampaignStatusEnum"];
            /** Комментарий администратора */
            admin_comment?: string;
            /** Название */
            title?: string;
            /**
             * Логотип акции
             * Format: uri
             */
            logo_image?: string;
            /**
             * Изображение акции
             * Format: uri
             */
            campaign_image?: string;
            /** Короткое описание */
            short_description?: string;
            /** Текст наклейки */
            sticker_text?: string;
            /** Вознаграждение */
            award?: number;
            /** Квота участников */
            quota?: number;
            /**
             * Дата окончания акции
             * Format: date-time
             */
            end_date?: string;
            /**
             * Дата одобрения акции
             * Format: date
             */
            approve_date?: string | null;
            /**
             * Баланс акции
             * Format: decimal
             */
            campaign_balance?: string;
            /** Порядковый номер */
            num?: number;
            /** Рекламодатель */
            advertiser?: number;
        };
        Slide: {
            readonly id: number;
            /** Заголовок */
            title: string;
            /** Текст */
            text?: string;
            /** Текст кнопки */
            btn_text?: string;
            /** URL кнопки */
            btn_url?: string;
            /**
             * Картинка
             * Format: uri
             */
            img: string;
            /**
             * Картинка для мобильных
             * Format: uri
             */
            img_mob?: string;
            /**
             * Картинка для планшетов
             * Format: uri
             */
            img_tablet?: string;
            /**
             * Иконка
             * Format: uri
             */
            icon?: string;
            /** Сортировка */
            rank?: number;
            slider: number;
        };
        SliderWithSlides: {
            readonly id: number;
            /** Название */
            title: string;
            /** Код */
            slug: string;
            readonly slides: components["schemas"]["Slide"][];
        };
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_campaigns_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"][];
                };
            };
        };
    };
    api_v1_campaigns_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Campaign"];
                "application/x-www-form-urlencoded": components["schemas"]["Campaign"];
                "multipart/form-data": components["schemas"]["Campaign"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
        };
    };
    api_v1_campaigns_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Акция. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
        };
    };
    api_v1_campaigns_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Акция. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Campaign"];
                "application/x-www-form-urlencoded": components["schemas"]["Campaign"];
                "multipart/form-data": components["schemas"]["Campaign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
        };
    };
    api_v1_campaigns_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Акция. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_campaigns_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Акция. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCampaign"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCampaign"];
                "multipart/form-data": components["schemas"]["PatchedCampaign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
        };
    };
    api_v1_sliders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SliderWithSlides"];
                };
            };
        };
    };
    api_v1_sliders_slides_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slide"][];
                };
            };
        };
    };
    api_v1_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    api_v1_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
}
